In [2]:
import csv

with open("C:/Users/User/Desktop/csv.s1/Sport car price.csv","r") as file:
    data=csv.reader(file)
    i=0
    for line1 in data:
        # print(line1[0])
        if  line1[0] == "Ferrari"  : 
            print(line1[0],line1[7])

Ferrari 3,33,750
Ferrari 6,25,000
Ferrari 2,22,000
Ferrari 6,25,000
Ferrari 2,22,000
Ferrari 2,74,280
Ferrari 6,25,000
Ferrari 2,22,000
Ferrari 2,19,750
Ferrari 2,76,550
Ferrari 2,22,620
Ferrari 5,07,000
Ferrari 2,76,550
Ferrari 2,74,280
Ferrari 6,25,000
Ferrari 3,63,730
Ferrari 2,18,750
Ferrari 6,25,000
Ferrari 6,25,000
Ferrari 2,76,550
Ferrari 2,18,750
Ferrari 2,74,280
Ferrari 2,18,750
Ferrari 2,15,000
Ferrari 2,80,000
Ferrari 6,25,000
Ferrari 2,74,280
Ferrari 6,25,000
Ferrari 2,45,000
Ferrari 2,22,630
Ferrari 6,25,000
Ferrari 6,25,000
Ferrari 3,40,000
Ferrari 6,25,000
Ferrari 2,22,630
Ferrari 6,25,000
Ferrari 6,25,000
Ferrari 6,25,000
Ferrari 2,50,000
Ferrari 2,45,000
Ferrari 2,74,280
Ferrari 6,25,000
Ferrari 2,35,000
Ferrari 6,25,000
Ferrari 6,25,000
Ferrari 6,25,000
Ferrari 2,22,620
Ferrari 6,25,000
Ferrari 2,75,000
Ferrari 2,74,390
Ferrari 6,25,000
Ferrari 2,74,280
Ferrari 6,25,000
Ferrari 3,33,750
Ferrari 6,25,000

In [4]:
import csv

with open("C:/Users/User/Desktop/csv.s1/Travel details dataset.csv","r" ) as file_handler:
    data_sheet=csv.reader(file_handler)
    i=0
    for line1 in data_sheet:
        print(line1)# print all travel details 
        i=i+1
        if i!=11: # it will loop untill 10
            print(i) # after looping it will print 10 Travel details
            continue 
        break # break at the 10th loop

['ï»¿Trip ID', 'Destination', 'Start date', 'End date', 'Duration (days)', 'Traveler name', 'Traveler age', 'Traveler gender', 'Traveler nationality', 'Accommodation type', 'Accommodation cost', 'Transportation type', 'Transportation cost']
1
['1', 'London, UK', '05-01-2023', '05-08-2023', '7', 'John Smith', '35', 'Male', 'American', 'Hotel', '1200', 'Flight', '600']
2
['2', 'Phuket, Thailand', '6/15/2023', '6/20/2023', '5', 'Jane Doe', '28', 'Female', 'Canadian', 'Resort', '800', 'Flight', '500']
3
['3', 'Bali, Indonesia', '07-01-2023', '07-08-2023', '7', 'David Lee', '45', 'Male', 'Korean', 'Villa', '1000', 'Flight', '700']
4
['4', 'New York, USA', '8/15/2023', '8/29/2023', '14', 'Sarah Johnson', '29', 'Female', 'British', 'Hotel', '2000', 'Flight', '1000']
5
['5', 'Tokyo, Japan', '09-10-2023', '9/17/2023', '7', 'Kim Nguyen', '26', 'Female', 'Vietnamese', 'Airbnb', '700', 'Train', '200']
6
['6', 'Paris, France', '10-05-2023', '10-10-2023', '5', 'Michael Brown', '42', 'Male', 'American', 'Hotel', '1500', 'Flight', '800']
7
['7', 'Sydney, Australia', '11/20/2023', '11/30/2023', '10', 'Emily Davis', '33', 'Female', 'Australian', 'Hostel', '500', 'Flight', '1200']
8
['8', 'Rio de Janeiro, Brazil', '01-05-2024', '01-12-2024', '7', 'Lucas Santos', '25', 'Male', 'Brazilian', 'Airbnb', '900', 'Flight', '600']
9
['9', 'Amsterdam, Netherlands', '2/14/2024', '2/21/2024', '7', 'Laura Janssen', '31', 'Female', 'Dutch', 'Hotel', '1200', 'Train', '200']
10
['10', 'Dubai, United Arab Emirates', '03-10-2024', '3/17/2024', '7', 'Mohammed Ali', '39', 'Male', 'Emirati', 'Resort', '2500', 'Flight', '800']

In [5]:
import csv
i=0
with open("C:/Users/User/Desktop/csv.s1/Salary_Dataset_with_Extra_Features.csv","r") as data_set:
    data=csv.reader(data_set)
    for line2 in data:
        i=i+1
        # in hole data sheet only piking the particular state and there  lesser than or equale to 4.5ratings with salary pakage
        if line2[5]=="Kerala"and line2[0]<=str(4.5):
            print(line2[5],line2[1],line2[0],line2[3])

Kerala UST 4 400000
Kerala CareStack (Good Methods Global) 3.3 400000
Kerala Tata Consultancy Services 3.9 200000
Kerala TATA ELXSI 4 200000
Kerala Quest Global 3.1 300000
Kerala IBS Software 3.8 384000
Kerala Inpetro Technologies 3.7 120000
Kerala Tata Consultancy Services 3.9 400000
Kerala Infosys 3.3 400000
Kerala Cognizant Technology Solutions 3.8 588000
Kerala Wipro 3.8 444000
Kerala Oracle 3.9 400000
Kerala EMPLOYERS 4.1 100000
Kerala ABCDEF 3.9 500000
Kerala Conduent 3.1 516000
Kerala Boston Consulting Group 4.4 144000
Kerala IBS Software 3.8 240000
Kerala Finastra 3.9 600000
Kerala QBurst 4.5 500000
Kerala Envestnet 4.1 168000
Kerala Orion Innovation 3.7 288000
Kerala SFO Technologies 3.5 300000
Kerala RapidValue Solutions 4.1 800000
Kerala Flytxt 4 400000
Kerala Some 4 348000
Kerala Zafin 4.2 500000
Kerala Dexlock 4.4 312000
Kerala NEWAGESYS 4.1 216000
Kerala Cycloides 2.9 204000
Kerala Advenser 4.3 300000
Kerala Pac-Van 4 500000
Kerala PappyJoe 2.9 240000
Kerala Millennium EBS 4 900000
Kerala Aten 2.6 468000
Kerala HHB Systems 4.1 672000
Kerala Livewire Communications 4.5 300000
Kerala Infygen Technologies 2.9 792000
Kerala FGV EAESP Ventures 4 500000
Kerala Enive 3.9 684000
Kerala Unnicola 2.5 252000
Kerala Bhaskaran Pillai Technologies 3.9 800000
Kerala CRMantra 3.4 600000
Kerala Jo 3.9 300000
Kerala Sport BSO De Woerd 3.9 400000
Kerala BIJISH KUMAR 3.9 312000
Kerala The Millennium Laedan 3.9 100000
Kerala CareStack (Good Methods Global) 3.3 400000
Kerala Quest Global 3.1 828000
Kerala CareStack (Good Methods Global) 3.3 400000
Kerala QBurst 4.5 1080000
Kerala Nissan Digital 3.2 600000
Kerala CareStack (Good Methods Global) 3.3 1300000
Kerala Valorem Reply 4 1020000
Kerala Wipro 3.8 120000
Kerala PwC 3.9 600000
Kerala DONE by NONE 4 1000000
Kerala UST 4 2300000
Kerala Don't Know 3.9 2900000
Kerala Nissan Digital 3.2 600000
Kerala dâ€™Katia Software 2.8 300000
Kerala RPA Labs 4.2 800000
Kerala Rohith 3.9 400000
Kerala Huhu Solutions 4.3 500000
Kerala CFD Schuck 3.9 480000
Kerala Asiet 3 200000
Kerala Internet Society 3.5 684000
Kerala Cognizant Technology Solutions 3.8 700000
Kerala TATA ELXSI 4 552000
Kerala Finastra 3.9 768000
Kerala VVDN Technologies 3.5 600000
Kerala Xerox 3.3 1000000
Kerala RM 3.7 576000
Kerala ThinkPalm Technologies 3.9 1100000
Kerala Suyati Technologies 4.2 600000
Kerala Media Systems 4.4 828000
Kerala Tata Consultancy Services 3.9 1152000
Kerala Infosys 3.3 500000
Kerala Bharti Airtel 4.2 200000
Kerala UST 4 900000
Kerala IQVIA 3.9 696000
Kerala Nielsen 3.8 400000
Kerala Experion Technologies 4.4 800000
Kerala SOTI 3.5 600000
Kerala Los Angeles USD 3.7 684000
Kerala YZC 3.9 100000
Kerala CareStack (Good Methods Global) 3.3 1100000
Kerala TEST 3.2 1200000
Kerala CareStack (Good Methods Global) 3.3 696000
Kerala Envestnet 4.1 600000
Kerala CareStack (Good Methods Global) 3.3 400000
Kerala Linways Technologies 4.2 180000
Kerala Inpetro Technologies 3.7 400000
Kerala Fresher 4.1 228000
Kerala Reflections Info Systems 4.1 360000
Kerala Cognizant Technology Solutions 3.8 1000000

In [6]:
import csv 

with open("C:/Users/User/Desktop/csv.s1/Flipkart_mobile_brands_scraped_data.csv","r") as set:
    data=csv.reader(set)

    for line in data:
    
        if line[0]=="Xiaomi":
            print(line[0],line[1])
            if line[3]>="4GB":
                print(line[3])
                # if line[4]>=str(128):
                #     print(line[2],line[4])
                if line[7]>=str(30000):
                        print(line[7])

Xiaomi Mi 10
8 GB
59999
Xiaomi Mi 10
8 GB
Xiaomi Mi 10i
8 GB
Xiaomi Mi 10i
6 GB
Xiaomi Mi 10i
6 GB
Xiaomi Mi 10i
8 GB
Xiaomi Mi 10T
6 GB
39999
Xiaomi Mi 10T
8 GB
42999
Xiaomi Mi 10T
6 GB
39999
Xiaomi Mi 11 Lite
8 GB
Xiaomi Mi 11 Lite
6 GB
Xiaomi Mi 11 Lite
6 GB
Xiaomi Mi 11 Lite
8 GB
Xiaomi Mi 11 Lite
8 GB
Xiaomi Mi 11 Lite
6 GB
Xiaomi Mi 11X
8 GB
Xiaomi Mi 11X
6 GB
Xiaomi Mi 11X
8 GB
Xiaomi Mi 11X
6 GB
Xiaomi Mi 11X
6 GB
Xiaomi Mi 11X
8 GB
31983
Xiaomi Mi 11X
8 GB
Xiaomi MI 11X 5G
6 GB
Xiaomi MI 11X 5G
6 GB
Xiaomi MI 11X 5G
6 GB
Xiaomi Mi 11X Pro 5G
8 GB
37490
Xiaomi Mi 11X Pro 5G
8 GB
Xiaomi Mi 11X Pro 5G
8 GB
39990
Xiaomi Mi 11X Pro 5G
8 GB
Xiaomi Mi A2
6 GB
Xiaomi Mi A2
Xiaomi Mi A2
6 GB
Xiaomi Mi A2
Xiaomi Mi A2
6 GB
Xiaomi Mi A2
Xiaomi Mi A3
Xiaomi Mi A3
Xiaomi Mi A3
Xiaomi Mi Max 2
Xiaomi MI3
Xiaomi Redmi 5
Xiaomi Redmi 5
Xiaomi Redmi 5
Xiaomi Redmi 5
Xiaomi Redmi 6
Xiaomi Redmi 6 Pro
Xiaomi Redmi 6 Pro
Xiaomi Redmi 6 Pro
Xiaomi Redmi 6 Pro
Xiaomi Redmi 6A
Xiaomi Redmi 6A
Xiaomi Redmi 6A
Xiaomi Redmi 7
Xiaomi Redmi 7
Xiaomi Redmi 7A
Xiaomi Redmi 7A
Xiaomi Redmi 8
Xiaomi Redmi 8
Xiaomi Redmi 8
Xiaomi Redmi 8A
Xiaomi Redmi 8A
Xiaomi Redmi 8A Dual
Xiaomi Redmi 8A Dual
Xiaomi Redmi 8A Dual
Xiaomi Redmi 8A Dual
Xiaomi Redmi 8A Dual
Xiaomi Redmi 8A Dual
Xiaomi Redmi 9
Xiaomi Redmi 9
Xiaomi Redmi 9
Xiaomi Redmi 9
Xiaomi REDMI 9 Power
6 GB
Xiaomi REDMI 9 Power
Xiaomi REDMI 9 Power
Xiaomi REDMI 9 Power
6 GB
Xiaomi REDMI 9 Power
Xiaomi REDMI 9 Prime
Xiaomi REDMI 9 Prime
Xiaomi REDMI 9 Prime
Xiaomi REDMI 9 Prime
Xiaomi Redmi 9A
Xiaomi Redmi 9A
Xiaomi Redmi 9A
Xiaomi Redmi 9A
Xiaomi Redmi 9A
Xiaomi Redmi 9A
Xiaomi REDMI 9i
Xiaomi REDMI 9i
Xiaomi Redmi K20
6 GB
Xiaomi Redmi K20
6 GB
Xiaomi Redmi K20
6 GB
Xiaomi Redmi K20
6 GB
Xiaomi Redmi K20 Pro
6 GB
Xiaomi Redmi K20 Pro
8 GB
Xiaomi Redmi K20 Pro
6 GB
Xiaomi REDMI Note 10 Pro
6 GB
Xiaomi REDMI Note 10 Pro
6 GB
Xiaomi REDMI Note 10S
6 GB
Xiaomi REDMI Note 10S
6 GB
Xiaomi Redmi Note 4
Xiaomi Redmi Note 4
Xiaomi Redmi Note 4
Xiaomi Redmi Note 5
Xiaomi Redmi Note 5
Xiaomi Redmi Note 5
Xiaomi Redmi Note 5
Xiaomi Redmi Note 5 Pro
Xiaomi Redmi Note 5 Pro
6 GB
Xiaomi Redmi Note 5 Pro
Xiaomi Redmi Note 6 Pro
6 GB
Xiaomi Redmi Note 6 Pro
Xiaomi Redmi Note 6 Pro
Xiaomi Redmi Note 6 Pro
6 GB
Xiaomi Redmi Note 6 Pro
6 GB
Xiaomi Redmi Note 6 Pro
Xiaomi Redmi Note 6 Pro
Xiaomi Redmi Note 6 Pro
6 GB
Xiaomi Redmi Note 7
Xiaomi Redmi Note 7
Xiaomi Redmi Note 7
Xiaomi Redmi Note 7
Xiaomi Redmi Note 7
Xiaomi Redmi Note 7 Pro
Xiaomi Redmi Note 7 Pro
6 GB
Xiaomi Redmi Note 7 Pro
6 GB
Xiaomi Redmi Note 7 Pro
Xiaomi Redmi Note 7 Pro
6 GB
Xiaomi Redmi Note 7 Pro
6 GB
Xiaomi Redmi Note 7 Pro
6 GB
Xiaomi Redmi Note 7 Pro
Xiaomi Redmi Note 7 Pro
6 GB
Xiaomi Redmi Note 7S
Xiaomi Redmi Note 7S
Xiaomi Redmi Note 7S
Xiaomi Redmi Note 7S
Xiaomi Redmi Note 8
Xiaomi Redmi Note 8
Xiaomi Redmi Note 8
Xiaomi REDMI Note 9
Xiaomi REDMI Note 9
Xiaomi REDMI Note 9
Xiaomi REDMI Note 9
Xiaomi Redmi Note 9 Pro
Xiaomi Redmi Note 9 Pro
Xiaomi Redmi Note 9 Pro
6 GB
Xiaomi Redmi Note 9 Pro
Xiaomi Redmi Note 9 Pro
Xiaomi Redmi Note 9 Pro
Xiaomi Redmi Y1
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y2
Xiaomi Redmi Y3
Xiaomi Redmi Y3
Xiaomi Redmi Y3
Xiaomi Redmi Y3
Xiaomi Redmi Y3

In [7]:
import csv
with open("C:/Users/User/Desktop/csv.s1/indian_food.csv","r") as list:
    data=csv.reader(list)
    for line in data:
        # if line[7]=="Karnataka":
        #     print(line[7],line[0],line[5])
        if line[5]=="sweet" :
            print(line[5],line[0],line[7])

sweet Balu shahi West Bengal
sweet Boondi Rajasthan
sweet Gajar ka halwa Punjab
sweet Ghevar Rajasthan
sweet Gulab jamun West Bengal
sweet Imarti West Bengal
sweet Jalebi Uttar Pradesh
sweet Kaju katli -1
sweet Kalakand West Bengal
sweet Kheer -1
sweet Laddu -1
sweet Lassi Punjab
sweet Nankhatai -1
sweet Petha Uttar Pradesh
sweet Phirni Odisha
sweet Rabri Uttar Pradesh
sweet Sheera Maharashtra
sweet Singori Uttarakhand
sweet Sohan halwa Uttar Pradesh
sweet Sohan papdi Maharashtra
sweet Chhena jalebi Odisha
sweet Chhena kheeri Odisha
sweet Chhena poda Odisha
sweet Cham cham West Bengal
sweet Kheer sagar Odisha
sweet Ledikeni West Bengal
sweet Lyangcha Assam
sweet Malapua Bihar
sweet Mihidana West Bengal
sweet Misti doi West Bengal
sweet Pantua West Bengal
sweet Pithe Assam
sweet Rasabali Odisha
sweet Ras malai West Bengal
sweet Rasgulla West Bengal
sweet Sandesh West Bengal
sweet Adhirasam West Bengal
sweet Ariselu Andhra Pradesh
sweet Bandar laddu Andhra Pradesh
sweet Chikki Maharashtra
sweet Dharwad pedha Karnataka
sweet Double ka meetha Telangana
sweet Gavvalu Andhra Pradesh
sweet Kakinada khaja Andhra Pradesh
sweet Kuzhi paniyaram Kerala
sweet Mysore pak Karnataka
sweet Obbattu holige Karnataka
sweet Palathalikalu Andhra Pradesh
sweet Poornalu Andhra Pradesh
sweet Pongal Tamil Nadu
sweet Pootharekulu Andhra Pradesh
sweet Qubani ka meetha Telangana
sweet Sheer korma Telangana
sweet Unni Appam Tamil Nadu
sweet Kajjikaya Andhra Pradesh
sweet Anarsa Maharashtra
sweet Basundi Gujarat
sweet Dhondas Maharashtra
sweet Doodhpak Gujarat
sweet Mahim halwa Maharashtra
sweet Modak Maharashtra
sweet Shankarpali Maharashtra
sweet Shrikhand Maharashtra
sweet Sutar feni Maharashtra
sweet Chak Hao Kheer Manipur
sweet Dal makhani  Punjab
sweet Kulfi falooda -1
sweet Panjeeri Uttar Pradesh
sweet Shahi tukra Telangana
sweet Payasam -1
sweet Coconut vadi Maharashtra
sweet Dudhi halwa Gujarat
sweet Gud papdi Gujarat
sweet Halvasan Gujarat
sweet Mohanthal Gujarat
sweet Sukhdi Maharashtra
sweet Churma Ladoo Rajasthan
sweet Cheera Doi West Bengal
sweet Gheela Pitha Assam
sweet Goja West Bengal
sweet Hando Guri Assam
sweet Mishti Chholar Dal West Bengal
sweet Payokh Assam
sweet Til Pitha Assam
sweet Bebinca Goa
sweet Shufta Jammu & Kashmir
sweet Mawa Bati Madhya Pradesh
sweet Pinaca Goa

In [1]:
import csv
data=["NAME","ROLL NUMBER","MARKS","GRADE"]

rows=    [['GOURAV', '111', '80', 'A'], 
         ['SHANKER', '222', '95', 'A+'], 
         ['SAMARTH', '333', '96', 'A+'], 
         ['VINAYAK', '444', '90', 'A+'], 
         ['HEMANTH', '555', '85', 'A'], 
         ['RAJ', '666', '90', 'A']]

with open("a.csv","w" ) as csvfile:
   csvwriter = csv.writer(csvfile)
   csvwriter.writerow(data)
   csvwriter.writerows(rows)